apiVersion: apps/v1
kind: Deployment
metadata:
  name: ionic-frontend
spec:
  selector:
    matchLabels:
      deployment-name: ionic-frontend
  replicas: 2
  template:
    metadata:
      labels:
        deployment-name: ionic-frontend 
    spec:
      containers:
        - name: ionic-frontend-container
          image: ehyasin/b8it148:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: ionic-cluster-service
  name: ionic-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: ionic-cluster-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: ionic-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: ionic-cluster-service 
  name: ionic-cluster-service-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: load-balancer-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: ionic-frontend